/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdultChinese: typeof import('./../../components/Adult/adult-chinese.vue')['default']
    AdultEmby: typeof import('./../../components/Adult/adult-emby.vue')['default']
    AdultInventory: typeof import('./../../components/Adult/adult-inventory.vue')['default']
    AppProvider: typeof import('./../../components/AppProvider/index.vue')['default']
    AvChinese: typeof import('../../components/Adult/adult-chinese.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    EmbyCatalogedList: typeof import('./../../components/EmbyCatalogedList/index.vue')['default']
    EmbyPlayButton: typeof import('./../../components/EmbyPlayButton/index.vue')['default']
    HelloWorld: typeof import('./../../components/HelloWorld.vue')['default']
    Main: typeof import('./../../components/Search/main.vue')['default']
    OnlinePlay: typeof import('../../content/OnlinePlay/index.vue')['default']
    PendingUpdateChineseButton: typeof import('./../../components/PendingUpdateChineseButton/index.vue')['default']
    Search: typeof import('./../../components/Search/index.vue')['default']
    Site_btn: typeof import('../../content/OnlinePlay/site_btn.vue')['default']
    SvgIcon: typeof import('./../../components/SvgIcon/index.vue')['default']
    TorrentList: typeof import('./../../components/TorrentList/index.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
