/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdultChinese: typeof import('./../../components/Adult/adult-chinese.vue')['default']
    AdultEmby: typeof import('./../../components/Adult/adult-emby.vue')['default']
    AdultInventory: typeof import('./../../components/Adult/adult-inventory.vue')['default']
    AdultThumbnail: typeof import('./../../components/Adult/adult-thumbnail.vue')['default']
    AdultTorrent: typeof import('./../../components/Adult/adult-torrent.vue')['default']
    AppProvider: typeof import('./../../components/AppProvider/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IconLoading: typeof import('./../../components/Loading/icon-loading.vue')['default']
    PageLoading: typeof import('./../../components/Loading/page-loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SitePlay: typeof import('./../../components/site-play.vue')['default']
    SvgIcon: typeof import('./../../components/SvgIcon/index.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
